# Generated by Django 3.1.5 on 2021-01-23 02:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Club01', '0002_auto_20210123_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingminutes',
            name='meetingattendance',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
