# Generated by Django 3.1.5 on 2021-01-23 23:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Club01', '0003_auto_20210123_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingminutes',
            name='meetingattendance',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
