# Generated by Django 3.1.5 on 2021-02-01 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Club01', '0004_auto_20210123_2353'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resource',
            options={'verbose_name_plural': 'Resources'},
        ),
        migrations.AlterModelTable(
            name='resource',
            table='Resource',
        ),
    ]
