# Generated by Django 3.1.5 on 2021-02-07 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Club01', '0005_auto_20210201_0457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingminutes',
            name='meetingminutesText',
        ),
    ]
