# Generated by Django 3.1.5 on 2021-02-07 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Club01', '0006_remove_meetingminutes_meetingminutestext'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingminutes',
            name='meetingminutesText',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
